name: ${CONTAINER_NAME}
services:
    app:
        build: ./app
        container_name: ${CONTAINER_NAME}.app
        user: ${CONTAINER_PUID}:${CONTAINER_PGID}
        volumes:
            - ../app/:/var/www/app:cached
            - ./app/php.ini:/usr/local/etc/php/php.ini:ro
            - ./app/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:ro
        extra_hosts:
            - host.docker.internal:host-gateway
        logging:
            options:
                max-size: 10m
                max-file: 3
    app-worker:
        build: ./app-worker
        container_name: ${CONTAINER_NAME}.app-worker
        volumes:
            - ../app/:/var/www/app:cached
            - ./app-worker/php.ini:/usr/local/etc/php/php.ini:ro
            - ./app-worker/supervisord.conf:/etc/supervisor/supervisord.conf:ro
            - ./app-worker/app.conf:/etc/supervisor/conf.d/app.conf:ro
        extra_hosts:
            - host.docker.internal:host-gateway
        logging:
            options:
                max-size: 10m
                max-file: 3
    nginx:
        build: ./nginx
        container_name: ${CONTAINER_NAME}.nginx
        ports:
            - ${NGINX_HTTP_PORT}:80
            - ${NGINX_HTTPS_PORT}:443
        volumes:
            - ../app/:/var/www/app:cached
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
        logging:
            options:
                max-size: 10m
                max-file: 3
    postgres:
        container_name: ${CONTAINER_NAME}.postgres
        image: postgres:16
        ports:
            - ${POSTGRES_PORT}:5432
        environment:
            - POSTGRES_PASSWORD=postgres
        logging:
            options:
                max-size: 10m
                max-file: 3
    adminer:
        image: adminer
        container_name: ${CONTAINER_NAME}.adminer
        ports:
            - ${ADMINER_PORT}:8080
        logging:
            options:
                max-size: 10m
                max-file: 3
