framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: '%env(EMAIL_SENDER_ADDRESS)%'
        headers:
            From: '%env(EMAIL_SENDER_NAME)% <%env(EMAIL_SENDER_ADDRESS)%>'
